name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v5
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - uses: leafo/gh-actions-luarocks@v2
      - name: Install test dependencies
        run: |
          luarocks install busted

      - name: Checkout vusted
        uses: actions/checkout@v2
        with:
          repository: notomo/vusted
          path: vusted

      - name: Add vusted to path
        run: |
          echo "::add-path::./vusted/bin"

      - uses: rhysd/action-setup-vim@v1.2.3
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run tests
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
        run: make test
